/**
 * CSS Build Script
 * Concatenates all CSS modules into a single styles.css file
 * Run: node build-css.js
 */

const fs = require('fs');
const path = require('path');

const modulesDir = path.join(__dirname, 'src', 'styles');
const outputFile = path.join(__dirname, 'styles.css');

// Order of CSS modules (important for cascade)
const moduleOrder = [
  '_variables.css',
  '_base.css',
  '_layout.css',
  '_titlebar.css',
  '_sidebar.css',
  '_user-info.css',
  '_navigation.css',
  '_cards.css',
  '_buttons.css',
  '_forms.css',
  '_status.css',
  '_toast.css',
  '_errors.css',
  '_modals.css',
  '_changelog.css',
  '_update.css',
  '_special-components.css',
  '_dlc.css',
  '_password-manager.css',
  '_animations.css',
  '_responsive.css',
  '_utilities.css'
];

let output = `/* ============================================
   MAKE YOUR LIFE EASIER - MAIN STYLESHEET
   ============================================
   
   Auto-generated from CSS modules in src/styles/
   Do not edit this file directly - edit the modules instead
   Run: node build-css.js to rebuild
   
   ============================================ */

`;

for (const module of moduleOrder) {
  const filePath = path.join(modulesDir, module);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    output += `\n/* === ${module} === */\n`;
    output += content;
    output += '\n';
    console.log(`✓ Added ${module}`);
  } else {
    console.warn(`⚠ Warning: ${module} not found`);
  }
}

fs.writeFileSync(outputFile, output, 'utf8');
console.log(`\n✓ Built styles.css (${(output.length / 1024).toFixed(1)} KB)`);
