name: Build and Release Electron App

on:
  push:
    tags: ['v*']
  workflow_dispatch:  # Επιτρέπει manual trigger

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Electron app
      run: npm run build-all
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.blockmap
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}