name: Publish Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build and Publish
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm run build-all
        npx electron-builder --win --publish always